apiVersion: v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: https://hub.docker.com/r/training/webapp/dockerfile
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
