apiVersion: v1
kind: Service
metadata:  
  name: webapp-service
spec:
  selector:    
    app: webapp
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30036
    protocol: TCP